name: AI Code Review Action
description:
  Automatically review code changes using OpenAI and provide detailed feedback
author: Your name or organization here

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: search
  color: blue

# Define your inputs here.
inputs:
  milliseconds:
    description: Your input description here
    required: true
    default: '1000'
  openai-api-key:
    description: 'OpenAI API key for code review'
    required: false

# Define your outputs here.
outputs:
  time:
    description: Your output description here

runs:
  using: node24
  main: dist/index.js
